version: '3.8'
services:
    scaffold-build:
        build:
            context: .
            dockerfile: Dockerfile.Node
        command: sh -c "rm -rf ./packages/hardhat/deployments && rm -rf ./packages/nextjs/contracts && yarn install"
        volumes:
            - ./smartcontracts:/workspace

    backend-build:
        build:
            context: .
            dockerfile: Dockerfile.Python
        command: pip3 install --no-cache-dir -r requirements.txt
        volumes:
            - ./backend:/workspace
