FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
	apt-get install -y python3-pip python3-dev python3.8-venv && \
	apt-get clean && \
	rm -rf /var/lib/apt/lists/*
RUN python3 -m pip install --upgrade pip

WORKDIR /workspace

COPY /offchain/requirements.txt /workspace/requirements.txt
RUN pip install -r requirements.txt

ENV PYTHONUNBUFFERED=1