version: '3.8'
services:
    scaffold-build:
        extends:
            file: common-services.yml
            service: scaffold-build

    scaffold-test:
        build:
            context: ./smartcontract
            dockerfile: Dockerfile
        command: yarn test
        volumes:
            - ./smartcontract:/smartcontract
        depends_on:
            scaffold-build:
                condition: service_completed_successfully
